### ISSUE TITLE
Deployment - Add S3 container for production mode

### ISSUE THREAD

**Issue by zsabri91** [COSC481W-2024Fall/MLite#23]
**User Story:**

As a user I want the system to have a secure and reliable way to store and access both datasets and models in production, so I can trust that my predictions are accurate and available whenever I need them.

**Persona:**

Users who depend on stable and consistent model performance for their tasks. Ken for example, a CTO of a startup, would want to keep his data secure and in a controlled environment, safe from bad-actors and technological issues (like an outage).

**Feature:**

- Configure an S3 container specifically for production environments.
- Ensure secure access and seamless integration with the production server.
- Implement best practices for S3 usage, such as versioning, access control, and encryption.

**Business Value:**

Setting up an S3 container for production mode will ensure that ML models can access necessary datasets and resources reliably and securely. This will enhance the robustness of the platform by providing consistent data storage and retrieval for production environments.

**Tasks:**

1. Research and configure an S3 container for the production environment.
2. Set up access control policies and encryption for secure data storage.
3. Integrate the S3 container with the production server to load models and datasets.
4. Test the configuration to ensure data can be loaded from S3 without issues.
5. Document the setup process, including configuration and integration steps.

**Acceptance Criteria:**

- The S3 container is set up and configured for production.
- Access control policies and encryption are correctly implemented.
- The production server can securely access and load models/data from the S3 container.
- Detailed documentation is available for future setup and troubleshooting.

**Acceptance Tests:**

- Confirm that the production server can successfully load models/data from the S3 container.
- Verify that access to the S3 container is secure, with proper access control and encryption.
- Test multiple scenarios to ensure data is retrieved smoothly without interruptions.

**Comment by sjiang1** [comment]
Will the deployment server be linked to the deployment page? If so, who will be responsible for that? If not, how to test the deployment server?

**Comment by Mohammad4844** [comment]
> Will the deployment server be linked to the deployment page? If so, who will be responsible for that? If not, how to test the deployment server?

Correction: was meant to say Production Server/App instead of deployment server. Made the correction.
