### ISSUE TITLE
Rails - Dataset viewer to preview first n rows of dataset

### ISSUE THREAD

**Issue by Mohammad4844** [COSC481W-2024Fall/MLite#24]
User Story:
As a user, I want to upload datasets and be able to see the first few and last few rows of the dataset.

Persona:
Users uploading datasets to manage, explore, and prepare them for machine learning workflows. Allison for example would find it to be easier and quicker to find information on a patient if there were a preview for each dataset.

Feature:

1. The ability to see the first few and last few rows for an uploaded dataset.

Business Value:
Having the ability to see the first few and last few rows of an uploaded dataset allows the users to quickly identify which dataset it is and quickly see a little of its contents.

Tasks

- Create a dataset viewer that will read the first few and last few rows of the dataset.
- Have the viewer display the first few rows.

Acceptance Criteria:

- Users can upload datasets (CSV or Excel).
- The viewer displays the appropriate information to the user.

Acceptance Tests:

- Users can upload valid datasets.
- Users can view the first few rows of the dataset and the last few rows.

**Comment by sjiang1** [comment]
I also want the dataset viewer to show the last few rows to make sure the dataset is uploaded correctly.

**Comment by sjiang1** [comment]
Just to be clear, will this be done in Sprint 2?

> I also want the dataset viewer to show the last few rows to make sure the dataset is uploaded correctly.

**Comment by Mohammad4844** [comment]
> Just to be clear, will this be done in Sprint 2?
> 
> > I also want the dataset viewer to show the last few rows to make sure the dataset is uploaded correctly.

Yes. Updated the PBI to reflect that.
