### ISSUE TITLE
Rails - Deployments inference form & page

### ISSUE THREAD

**Issue by Mohammad4844** [COSC481W-2024Fall/MLite#27]
User Story:
As a user, I would like to use my deployments. I'd want a form where I can input new data, and it will use the model to infer and render the response.

Persona:
Users with deployments they would like to use//interact with. Allison for example has patients that can show new symptoms that haven't been shown before so It would be necessary to be able to input that new data.

Feature:

1. Take deployments the user has already made and allow them to use a form to do inference from them.

Business Value:
Will allow users to actually use their models straight from our app.

Tasks

- Create a new inference page with a form.
- Connect the deployments page to the inference page to modify the deployments.

Acceptance Criteria

- Form will return a dummy response for now. Actual inference from deployments will be addressed in Sprint 3.

Acceptance Tests

- Users can add input to the fields and submit the form to get a dummy response

**Comment by sjiang1** [comment]
The user story itself is too short.
The feature is not clear to me. What does "manage deployments" mean?

**Comment by Mohammad4844** [comment]
> The user story itself is too short. The feature is not clear to me. What does "manage deployments" mean?

Updated it. How about now?

**Comment by sjiang1** [comment]
Very clear to me now.
